package com.hazem.boruto.presentation.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val EXTRA_SMALL_PADDING = 6.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val VERY_SMALL_LARGE_PADDING = 4.dp


val PAGER_INDICATOR_HEIGHT = 50.dp
val HERO_ITEM_HEIGHT = 400.dp
val FINISH_BUTTON_WIDTH = 150.dp
val NAME_PLACE_HOLDER_HEIGHT = 30.dp
val ABOUT_PLACE_HOLDER_HEIGHT = 15.dp
val RATING_PLACE_HOLDER_HEIGHT = 20.dp
val TOP_APP_BAR_HEIGHT = 56.dp
val MIN_SHEET_HEIGHT = 130.dp


val ERROR_IMAGE_SIZE = 120.dp
val ICON_INFO_SIZE = 32.dp

val EXPANDED_RADIUS_LEVEL=0.dp